"""Starter Interior Library — 70+ curated items with realistic Indian brand pricing.

Loaded on backend startup if the collection is empty. Admins can add/edit
via the admin UI; this is only a starter catalog to save typing.
"""
from typing import List, Dict, Any

INTERIOR_LIBRARY_STARTER: List[Dict[str, Any]] = [
    # --- Kitchen ---
    {"category": "Kitchen", "name": "Modular Kitchen — L-Shape (Basic)", "brand": "Sleek", "rate": 1500, "rate_unit": "per sqft",
     "warranty": "5 Years", "notes": "MDF carcass, laminate finish, soft-close hinges", "default_quantity": 40},
    {"category": "Kitchen", "name": "Modular Kitchen — L-Shape (Premium)", "brand": "Godrej Interio", "rate": 2200, "rate_unit": "per sqft",
     "warranty": "10 Years", "notes": "Plywood BWR carcass, acrylic finish, Blum hardware", "default_quantity": 40},
    {"category": "Kitchen", "name": "Modular Kitchen — U-Shape (Premium)", "brand": "Hafele", "rate": 2600, "rate_unit": "per sqft",
     "warranty": "10 Years", "notes": "Plywood BWP carcass, PU finish, Hettich Innotech drawers", "default_quantity": 55},
    {"category": "Kitchen", "name": "Kitchen Island Counter", "brand": "Custom", "rate": 45000, "rate_unit": "per unit",
     "notes": "Granite/quartz top, storage below"},
    {"category": "Kitchen", "name": "Auto-Clean Chimney 90cm", "brand": "Faber", "rate": 22000, "rate_unit": "per unit",
     "warranty": "3 Years", "notes": "1200 m3/hr suction, filterless auto-clean"},
    {"category": "Kitchen", "name": "Chimney 60cm", "brand": "Elica", "rate": 12500, "rate_unit": "per unit", "warranty": "1 Year"},
    {"category": "Kitchen", "name": "4-Burner Hob (Auto Ignition)", "brand": "Prestige", "rate": 14500, "rate_unit": "per unit",
     "warranty": "2 Years"},
    {"category": "Kitchen", "name": "Built-in Microwave 32L", "brand": "IFB", "rate": 25000, "rate_unit": "per unit", "warranty": "2 Years"},
    {"category": "Kitchen", "name": "Built-in Dishwasher 12-place", "brand": "Bosch", "rate": 42000, "rate_unit": "per unit",
     "warranty": "2 Years"},
    {"category": "Kitchen", "name": "Kitchen Sink — Single Bowl", "brand": "Nirali", "rate": 6500, "rate_unit": "per unit",
     "warranty": "10 Years", "notes": "Stainless steel 304 grade"},
    {"category": "Kitchen", "name": "Kitchen Sink — Double Bowl", "brand": "Franke", "rate": 12500, "rate_unit": "per unit",
     "warranty": "10 Years"},
    {"category": "Kitchen", "name": "Sink Faucet (Pull-out)", "brand": "Jaquar", "rate": 8500, "rate_unit": "per unit", "warranty": "10 Years"},
    {"category": "Kitchen", "name": "Kitchen Countertop — Granite", "brand": "Local", "rate": 220, "rate_unit": "per sqft",
     "notes": "20mm thick, edge polished", "default_quantity": 30},
    {"category": "Kitchen", "name": "Kitchen Countertop — Quartz", "brand": "Kalinga Stone", "rate": 480, "rate_unit": "per sqft",
     "warranty": "10 Years", "notes": "18mm engineered stone", "default_quantity": 30},
    {"category": "Kitchen", "name": "Backsplash Tiles (Digital Glazed)", "brand": "Kajaria", "rate": 85, "rate_unit": "per sqft",
     "default_quantity": 25},

    # --- Wardrobes ---
    {"category": "Wardrobes", "name": "3-Door Wardrobe (Sliding)", "brand": "Godrej Interio", "rate": 1600, "rate_unit": "per sqft",
     "warranty": "5 Years", "notes": "Plywood carcass, laminate finish, mirror on one shutter", "default_quantity": 50},
    {"category": "Wardrobes", "name": "4-Door Wardrobe (Openable)", "brand": "Sleek", "rate": 1800, "rate_unit": "per sqft",
     "warranty": "5 Years", "notes": "Plywood BWR, veneer + acrylic combo", "default_quantity": 65},
    {"category": "Wardrobes", "name": "Walk-in Wardrobe (Premium)", "brand": "Hafele", "rate": 2400, "rate_unit": "per sqft",
     "warranty": "10 Years", "notes": "Modular units, LED strips, drawer inserts", "default_quantity": 80},
    {"category": "Wardrobes", "name": "Loft Storage Above Wardrobe", "brand": "Custom", "rate": 900, "rate_unit": "per sqft",
     "notes": "Standard 24 inch depth", "default_quantity": 20},
    {"category": "Wardrobes", "name": "Shoe Rack — Entry Hall", "brand": "Custom", "rate": 18000, "rate_unit": "per unit",
     "notes": "Wall-mounted, 5 shelves, laminate finish"},
    {"category": "Wardrobes", "name": "Study Table + Storage Combo", "brand": "Custom", "rate": 35000, "rate_unit": "per unit",
     "notes": "6ft desk with drawer + wall storage"},

    # --- Bathroom ---
    {"category": "Bathroom", "name": "Wall-Hung EWC + Concealed Cistern", "brand": "Jaquar", "rate": 18500, "rate_unit": "per unit",
     "warranty": "10 Years", "notes": "Includes flush plate + P-trap"},
    {"category": "Bathroom", "name": "Wall-Hung EWC (Premium)", "brand": "Kohler", "rate": 28000, "rate_unit": "per unit",
     "warranty": "10 Years"},
    {"category": "Bathroom", "name": "Basin — Counter-top", "brand": "Jaquar", "rate": 6500, "rate_unit": "per unit"},
    {"category": "Bathroom", "name": "Basin — Wall-hung", "brand": "Kohler", "rate": 9500, "rate_unit": "per unit", "warranty": "5 Years"},
    {"category": "Bathroom", "name": "Basin Mixer Tap", "brand": "Jaquar", "rate": 4500, "rate_unit": "per unit", "warranty": "10 Years"},
    {"category": "Bathroom", "name": "Overhead Rain Shower + Diverter", "brand": "Jaquar Continental", "rate": 12500, "rate_unit": "per unit",
     "warranty": "10 Years"},
    {"category": "Bathroom", "name": "Shower Enclosure — Glass Partition", "brand": "Ozone", "rate": 22000, "rate_unit": "per unit",
     "notes": "Toughened 10mm glass, frameless"},
    {"category": "Bathroom", "name": "Bathroom Wall Tiles", "brand": "Kajaria", "rate": 65, "rate_unit": "per sqft",
     "notes": "Digital glazed vitrified, 600x1200mm", "default_quantity": 120},
    {"category": "Bathroom", "name": "Bathroom Floor Tiles (Anti-skid)", "brand": "Somany", "rate": 55, "rate_unit": "per sqft",
     "default_quantity": 40},
    {"category": "Bathroom", "name": "Vanity Cabinet (Waterproof)", "brand": "Custom", "rate": 22000, "rate_unit": "per unit",
     "notes": "WPC/marine ply body, laminate finish"},
    {"category": "Bathroom", "name": "Mirror with LED Backlight", "brand": "Ozone", "rate": 12000, "rate_unit": "per unit",
     "notes": "Touch sensor, anti-fog, IP44"},
    {"category": "Bathroom", "name": "Geyser 25L (5-star)", "brand": "AO Smith", "rate": 18000, "rate_unit": "per unit",
     "warranty": "7 Years tank"},
    {"category": "Bathroom", "name": "Exhaust Fan", "brand": "Havells", "rate": 2500, "rate_unit": "per unit", "warranty": "2 Years"},

    # --- Lighting ---
    {"category": "Lighting", "name": "LED Ceiling Downlight 12W", "brand": "Philips", "rate": 750, "rate_unit": "per unit",
     "warranty": "3 Years", "default_quantity": 30},
    {"category": "Lighting", "name": "LED Ceiling Downlight 18W (Premium)", "brand": "Wipro", "rate": 1250, "rate_unit": "per unit",
     "warranty": "3 Years", "default_quantity": 20},
    {"category": "Lighting", "name": "Cove/Profile LED Strip 5m", "brand": "Syska", "rate": 4500, "rate_unit": "per unit",
     "warranty": "2 Years", "notes": "Warm white or RGB, dimmable"},
    {"category": "Lighting", "name": "Designer Pendant Light — Dining", "brand": "Fabbian", "rate": 22000, "rate_unit": "per unit"},
    {"category": "Lighting", "name": "Wall Sconce (LED)", "brand": "Havells", "rate": 3500, "rate_unit": "per unit", "warranty": "2 Years"},
    {"category": "Lighting", "name": "Ceiling Fan — BLDC", "brand": "Atomberg", "rate": 6500, "rate_unit": "per unit",
     "warranty": "3 Years + Motor 10 Years"},
    {"category": "Lighting", "name": "Smart Track Lighting — 3m", "brand": "Philips Hue", "rate": 28000, "rate_unit": "per unit",
     "notes": "16M colors, voice control"},
    {"category": "Lighting", "name": "Chandelier — Living Room", "brand": "Local Premium", "rate": 55000, "rate_unit": "per unit"},

    # --- Furnishings ---
    {"category": "Furnishings", "name": "Motorised Window Blinds", "brand": "Somfy", "rate": 850, "rate_unit": "per sqft",
     "warranty": "5 Years", "notes": "Roller blinds with tubular motor", "default_quantity": 60},
    {"category": "Furnishings", "name": "Curtains + Rod Fittings", "brand": "D'Decor", "rate": 450, "rate_unit": "per sqft",
     "default_quantity": 100},
    {"category": "Furnishings", "name": "Sofa — 3+2 Seater", "brand": "Godrej Interio", "rate": 85000, "rate_unit": "per unit",
     "notes": "Fabric or leatherette, 5 year frame warranty"},
    {"category": "Furnishings", "name": "Dining Table 6-Seater + Chairs", "brand": "@Home", "rate": 65000, "rate_unit": "per unit"},
    {"category": "Furnishings", "name": "TV Wall Panel with Storage", "brand": "Custom", "rate": 1400, "rate_unit": "per sqft",
     "notes": "Veneer + laminate combo", "default_quantity": 45},
    {"category": "Furnishings", "name": "Wallpaper (Designer)", "brand": "Excel", "rate": 250, "rate_unit": "per sqft",
     "default_quantity": 80},
    {"category": "Furnishings", "name": "Wall Cladding — Wood Panels", "brand": "Merino", "rate": 350, "rate_unit": "per sqft",
     "default_quantity": 50},

    # --- Doors & Windows ---
    {"category": "Doors & Windows", "name": "Main Door — Teak Wood", "brand": "Local Master Carpenter", "rate": 55000, "rate_unit": "per unit",
     "notes": "42mm thick, digital lock, teakwood frame"},
    {"category": "Doors & Windows", "name": "Internal Door (Flush)", "brand": "Century Ply", "rate": 8500, "rate_unit": "per unit",
     "warranty": "10 Years", "notes": "35mm BWR flush door, laminate finish", "default_quantity": 6},
    {"category": "Doors & Windows", "name": "Bathroom Door (WPC)", "brand": "Rajshri", "rate": 6500, "rate_unit": "per unit",
     "notes": "Waterproof composite, powder-coated frame", "default_quantity": 4},
    {"category": "Doors & Windows", "name": "Sliding UPVC Window (3-track)", "brand": "Fenesta", "rate": 550, "rate_unit": "per sqft",
     "warranty": "10 Years", "notes": "Double glazed, mosquito mesh", "default_quantity": 120},
    {"category": "Doors & Windows", "name": "Casement Aluminium Window", "brand": "Aluplast", "rate": 480, "rate_unit": "per sqft",
     "default_quantity": 60},
    {"category": "Doors & Windows", "name": "Smart Digital Door Lock", "brand": "Yale", "rate": 22000, "rate_unit": "per unit",
     "warranty": "2 Years", "notes": "Fingerprint + PIN + card + app"},

    # --- Electrical / Smart Home ---
    {"category": "Electrical", "name": "Modular Switches & Sockets", "brand": "Anchor Roma", "rate": 55, "rate_unit": "per point",
     "warranty": "10 Years", "default_quantity": 120},
    {"category": "Electrical", "name": "Premium Modular Switches", "brand": "Legrand Myrius", "rate": 145, "rate_unit": "per point",
     "warranty": "10 Years", "default_quantity": 80},
    {"category": "Electrical", "name": "Smart Home Switches", "brand": "Wipro Smart", "rate": 1800, "rate_unit": "per unit",
     "notes": "WiFi controlled, Alexa/Google", "default_quantity": 20},
    {"category": "Electrical", "name": "House Wiring — Copper", "brand": "Havells", "rate": 22, "rate_unit": "per sqft built-up",
     "warranty": "20 Years", "default_quantity": 1200},
    {"category": "Electrical", "name": "MCB Distribution Board", "brand": "Schneider", "rate": 12500, "rate_unit": "per unit",
     "notes": "18-way with RCCB, ISI marked"},
    {"category": "Electrical", "name": "Home Automation Hub", "brand": "Hogar Controls", "rate": 65000, "rate_unit": "per unit",
     "notes": "Central controller, app + voice"},
    {"category": "Electrical", "name": "CCTV — 4 Camera IP System", "brand": "CP Plus", "rate": 42000, "rate_unit": "per system",
     "warranty": "2 Years", "notes": "2MP HD cameras, 1TB NVR"},
    {"category": "Electrical", "name": "Video Door Phone", "brand": "Godrej Solus", "rate": 18500, "rate_unit": "per unit",
     "warranty": "2 Years"},

    # --- Flooring ---
    {"category": "Flooring", "name": "Vitrified Tiles — Living", "brand": "Kajaria", "rate": 85, "rate_unit": "per sqft",
     "notes": "800x800mm double-charge, PEI 4", "default_quantity": 400},
    {"category": "Flooring", "name": "Premium Vitrified Tiles", "brand": "Simpolo", "rate": 145, "rate_unit": "per sqft",
     "notes": "1200x1800mm marble finish", "default_quantity": 400},
    {"category": "Flooring", "name": "Italian Marble Flooring", "brand": "Imported", "rate": 380, "rate_unit": "per sqft",
     "notes": "Statuario or Botticino, 18mm thick", "default_quantity": 200},
    {"category": "Flooring", "name": "Engineered Wood Flooring", "brand": "Pergo", "rate": 250, "rate_unit": "per sqft",
     "warranty": "10 Years", "default_quantity": 200},
    {"category": "Flooring", "name": "SPC Vinyl Flooring", "brand": "Welspun", "rate": 120, "rate_unit": "per sqft",
     "warranty": "5 Years", "default_quantity": 200},

    # --- False Ceiling & Paint ---
    {"category": "Ceiling & Paint", "name": "Gypsum False Ceiling (Simple)", "brand": "Saint Gobain Gyproc", "rate": 85, "rate_unit": "per sqft",
     "default_quantity": 600},
    {"category": "Ceiling & Paint", "name": "Gypsum + POP Cove (Designer)", "brand": "Custom", "rate": 145, "rate_unit": "per sqft",
     "default_quantity": 400},
    {"category": "Ceiling & Paint", "name": "Interior Paint — Emulsion", "brand": "Asian Paints Royale", "rate": 32, "rate_unit": "per sqft",
     "warranty": "5 Years", "default_quantity": 1800},
    {"category": "Ceiling & Paint", "name": "Interior Paint — Luxury", "brand": "Asian Paints Royale Luxury", "rate": 58, "rate_unit": "per sqft",
     "warranty": "7 Years", "default_quantity": 1200},
    {"category": "Ceiling & Paint", "name": "Texture Paint (Feature Wall)", "brand": "Berger Silk", "rate": 145, "rate_unit": "per sqft",
     "default_quantity": 150},
    {"category": "Ceiling & Paint", "name": "Exterior Paint (Weatherproof)", "brand": "Asian Apex Ultima", "rate": 42, "rate_unit": "per sqft",
     "warranty": "10 Years", "default_quantity": 1400},
]
